/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  BigInts,
  BigIntsInterface,
} from "../../../../../filecoin-solidity-api/contracts/v0.8/utils/BigInts";

const _abi = [
  {
    inputs: [],
    name: "NegativeValueNotAllowed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f58bcf420e5fb2eef550a188a3dc295daadb06780cff4f23fb229e8bd1cd1ed064736f6c63430008140033";

type BigIntsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BigIntsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BigInts__factory extends ContractFactory {
  constructor(...args: BigIntsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BigInts & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BigInts__factory {
    return super.connect(runner) as BigInts__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BigIntsInterface {
    return new Interface(_abi) as BigIntsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BigInts {
    return new Contract(address, _abi, runner) as unknown as BigInts;
  }
}
