/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  FilAddresses,
  FilAddressesInterface,
} from "../../../../../filecoin-solidity-api/contracts/v0.8/utils/FilAddresses";

const _abi = [
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122096e5d53c33f9aff095173520d36999395e36f92c522e1967b837b29e1c3ef58164736f6c63430008140033";

type FilAddressesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FilAddressesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FilAddresses__factory extends ContractFactory {
  constructor(...args: FilAddressesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FilAddresses & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FilAddresses__factory {
    return super.connect(runner) as FilAddresses__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FilAddressesInterface {
    return new Interface(_abi) as FilAddressesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FilAddresses {
    return new Contract(address, _abi, runner) as unknown as FilAddresses;
  }
}
