/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "FilecoinCIDStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FilecoinCIDStore__factory>;
    getContractFactory(
      name: "Actor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Actor__factory>;
    getContractFactory(
      name: "BigInts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BigInts__factory>;
    getContractFactory(
      name: "FilAddresses",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FilAddresses__factory>;
    getContractFactory(
      name: "Misc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Misc__factory>;

    getContractAt(
      name: "FilecoinCIDStore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FilecoinCIDStore>;
    getContractAt(
      name: "Actor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Actor>;
    getContractAt(
      name: "BigInts",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BigInts>;
    getContractAt(
      name: "FilAddresses",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FilAddresses>;
    getContractAt(
      name: "Misc",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Misc>;

    deployContract(
      name: "FilecoinCIDStore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FilecoinCIDStore>;
    deployContract(
      name: "Actor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Actor>;
    deployContract(
      name: "BigInts",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigInts>;
    deployContract(
      name: "FilAddresses",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FilAddresses>;
    deployContract(
      name: "Misc",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Misc>;

    deployContract(
      name: "FilecoinCIDStore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FilecoinCIDStore>;
    deployContract(
      name: "Actor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Actor>;
    deployContract(
      name: "BigInts",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BigInts>;
    deployContract(
      name: "FilAddresses",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FilAddresses>;
    deployContract(
      name: "Misc",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Misc>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
